apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "hello-api.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hello-api.selector" (dict "root" . "component" "redis") | nindent 4 }}
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "hello-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hello-api.selector" (dict "root" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-api.selector" (dict "root" . "component" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
